import CarnesImages from '../../../assets/img/carnes/index.js';

const carnes = [
  {
    id: "res-001",
    nombre: "Bife de Chorizo",
    descripcion: "Corte jugoso y tierno, ideal para asados.",
    categoria: "res",
    corte: "Res",
    precio: 1500,
    precio_unitario: 1500,
    cantidad: 1,
    unidad: "kg",
    stock: 25,
    max_por_pedido: 5,
    activo: true,
    imagen: CarnesImages.carne1,
  },
  {
    id: "cerdo-001",
    nombre: "Costillas de Cerdo",
    descripcion: "Perfectas para barbacoa, con sabor intenso.",
    categoria: "cerdo",
    corte: "Cerdo",
    precio: 1200,
    precio_unitario: 1200,
    cantidad: 1,
    unidad: "kg",
    stock: 20,
    max_por_pedido: 4,
    activo: true,
    imagen: CarnesImages.carne2,
  },
  {
    id: "pollo-001",
    nombre: "Pechuga de Pollo",
    descripcion: "Corte magro y suave, perfecto para salteados.",
    categoria: "pollo",
    corte: "Pollo",
    precio: 800,
    precio_unitario: 800,
    cantidad: 1,
    unidad: "kg",
    stock: 30,
    max_por_pedido: 6,
    activo: true,
    imagen: CarnesImages.carne3,
  },
  {
    id: "res-002",
    nombre: "Lomo Vetado",
    descripcion: "Corte premium con vetas de grasa para mayor sabor.",
    categoria: "res",
    corte: "Res",
    precio: 2000,
    precio_unitario: 2000,
    cantidad: 1,
    unidad: "kg",
    stock: 15,
    max_por_pedido: 3,
    activo: true,
    imagen: CarnesImages.carne4,
  },
  {
    id: "cerdo-002",
    nombre: "Chuletas de Cerdo",
    descripcion: "Corte versátil, ideal para asar o freír.",
    categoria: "cerdo",
    corte: "Cerdo",
    precio: 1100,
    precio_unitario: 1100,
    cantidad: 1,
    unidad: "kg",
    stock: 18,
    max_por_pedido: 4,
    activo: true,
    imagen: CarnesImages.carne5,
  },
  {
    id: "pollo-002",
    nombre: "Alitas de Pollo",
    descripcion: "Corte pequeño y sabroso, perfecto para aperitivos.",
    categoria: "pollo",
    corte: "Pollo",
    precio: 600,
    precio_unitario: 600,
    cantidad: 1,
    unidad: "kg",
    stock: 40,
    max_por_pedido: 8,
    activo: true,
    imagen: CarnesImages.carneslobby,
  },
  {
    id: "res-003",
    nombre: "Carne Molida Premium",
    descripcion: "Corte versátil para hamburguesas y salsas.",
    categoria: "res",
    corte: "Res",
    precio: 900,
    precio_unitario: 900,
    cantidad: 1,
    unidad: "kg",
    stock: 35,
    max_por_pedido: 6,
    activo: true,
    imagen: CarnesImages.carnica,
  },
  {
    id: "res-004",
    nombre: "Carne Pres",
    descripcion: "Ideal para parrilla y asados especiales.",
    categoria: "res",
    corte: "Res",
    precio: 900,
    precio_unitario: 900,
    cantidad: 1,
    unidad: "kg",
    stock: 22,
    max_por_pedido: 5,
    activo: true,
    imagen: CarnesImages.carnes6,
  },
  {
    id: "res-005",
    nombre: "Carne a la parrilla",
    descripcion: "Corte especial para parrilla gourmet.",
    categoria: "res",
    corte: "Res",
    precio: 900,
    precio_unitario: 900,
    cantidad: 1,
    unidad: "kg",
    stock: 20,
    max_por_pedido: 5,
    activo: true,
    imagen: CarnesImages.grilled,
  },
  {
    id: "res-006",
    nombre: "Black Steak",
    descripcion: "Corte premium selección especial.",
    categoria: "res",
    corte: "Res",
    precio: 1400,
    precio_unitario: 1400,
    cantidad: 1,
    unidad: "kg",
    stock: 10,
    max_por_pedido: 2,
    activo: true,
    imagen: CarnesImages.blackSteak,
  },
  {
    id: "wagyu-001",
    nombre: "Wagyu A5",
    descripcion: "Carne Wagyu de máxima calidad.",
    categoria: "wagyu",
    corte: "Res",
    precio: 3500,
    precio_unitario: 3500,
    cantidad: 1,
    unidad: "kg",
    stock: 5,
    max_por_pedido: 1,
    activo: true,
    imagen: CarnesImages.wagyu1,
  },
  {
    id: "wagyu-002",
    nombre: "Wagyu Premium",
    descripcion: "Selección premium Wagyu.",
    categoria: "wagyu",
    corte: "Res",
    precio: 3200,
    precio_unitario: 3200,
    cantidad: 1,
    unidad: "kg",
    stock: 6,
    max_por_pedido: 1,
    activo: true,
    imagen: CarnesImages.wagyu2,
  },
  {
    id: "wagyu-003",
    nombre: "Wagyu Black Label",
    descripcion: "Edición especial Wagyu.",
    categoria: "wagyu",
    corte: "Res",
    precio: 3800,
    precio_unitario: 3800,
    cantidad: 1,
    unidad: "kg",
    stock: 3,
    max_por_pedido: 1,
    activo: true,
    imagen: CarnesImages.wagyu4,
  },
];

export default carnes;